### ISSUE TITLE
Rethinkdb

### ISSUE THREAD

**Issue by alexisvincent** [RisingStack/graffiti#11]
Whats the status on the rethinkdb adapter?

**Comment by gergelyke** [comment]
we are finalizing the mongoose one with Relay support - sadly we couldn't start working on it as of now

**Comment by alexisvincent** [comment]
I see

**Comment by gregbenner** [comment]
+1

**Comment by rafaeljesus** [comment]
I think it does not worth any more as RethinkDB is [shutting down]( http://www.defstartup.org/2017/01/18/why-rethinkdb-failed.html])
