### ISSUE TITLE
Combine multiple scheme sources?

### ISSUE THREAD

**Issue by jontonsoup** [RisingStack/graffiti#14]
I have a use case where I'm using a hand built schema (which talks to other APIs) and a graffiti mongoose schema. I'd like to be able to combine them into one endpoint. Is this possible at the moment?

Thanks,
Jon

**Comment by tothandras** [comment]
@jontonsoup In the [latest](https://github.com/graphql/graphql-js/releases/tag/v0.4.13) `graphql-js` release there is a [function](https://github.com/graphql/graphql-js/pull/227) just for this. I couldn't try it out myself, but it promises what you are requesting.

**Comment by jontonsoup** [comment]
@tothandras awesome! I'll take a look at that.

**Comment by tothandras** [comment]
@jontonsoup Let me know how it works! ;)

**Comment by jontonsoup** [comment]
@tothandras did a quick check -- seems like my schema is incompatible with the graffiti generated one (although I'm not sure why). They don't merge properly. 

It seems like its not designed to merge two schemas directly if you look at the chatter on the PR.

**Comment by tothandras** [comment]
@jontonsoup I see. I was expecting it to be more powerful. Then we can add the option to pass in fields to `getSchema`.
