### ISSUE TITLE
Is it possible to use with Node 0.12.x?

### ISSUE THREAD

**Issue by voronianski** [RisingStack/graffiti#15]
I have the following error in console:

```bash
/Users/dmitri/myapp/node_modules/@risingstack/graffiti/node_modules/boom/lib/index.js:5
const Http = require('http');
^^^^^
SyntaxError: Use of const in strict mode.
```

**Comment by tothandras** [comment]
I encourage you to update to 4.*. :) It's one of the dependencies (boom) that requires >= node 4.0. You can also try to run it with the `--harmony` flag.
