### ISSUE TITLE
Query type in pre hook?

### ISSUE THREAD

**Issue by jontonsoup** [RisingStack/graffiti#17]
I'd like to be able to know what type of query I'm getting (mutation or query) in a pre hook so I can authorize based on that information. 

IE: I'm trying to enable mutations only for admins. Is this possible? 

Best,
Jon

**Comment by tothandras** [comment]
Have you tried to use the `mutation` [hook](https://github.com/RisingStack/graffiti-mongoose#resolve-hooks)?

**Comment by jontonsoup** [comment]
Whoops! I'm dumb.




Thanks!

**Comment by tothandras** [comment]
I am pretty sure, you are not. :)

**Comment by jontonsoup** [comment]
😁
