### ISSUE TITLE
Variables are not properly parsed from GraphiQL POST

### ISSUE THREAD

**Issue by zopf** [RisingStack/graffiti#19]
GraphiQL is sending along the `variables` field as a string, but graphql is expecting a JSON object.  Somewhere along the line, the `variables` string field needs to get converted to JSON, otherwise GraphQL never receives the variables!

Here is the offending line:
https://github.com/RisingStack/graffiti/blob/master/src/koa/koa.js#L32

Here's an example POST body getting passed over the network:
```
{
  "query":"mutation M($foo: updateUserInput!) { updateUser(input: $foo) { clientMutationId changedUser { id, gender } } }",
  "variables":"{ \"variables\": { \"foo\": { \"clientMutationId\": \"549b5e7c-0516-4fc9-8944-125401211592\", \"id\": \"VXNlcjo1NmFhYTM4OTZkZjhmMDgxNDM4ODliNzQ=\", \"gender\": \"female\" } } }"
}
```

The problem is that, by the time we get to the line referenced above, variables is still a string.  It needs to be a JSON object.  I'm just getting started with this stack, but it seems like you just need to JSON.parse() the `variables` object there, right?  Or is there somewhere else in the stack where it should be getting converted?

**Comment by zopf** [comment]
Here's an example of a potential solution:

https://github.com/wellth-app/graffiti/commit/bef6176ba9f88b8529eac953bec6b864be92a5c1

**Comment by tothandras** [comment]
@zopf Thanks for the report! Can you try it with version `3.0.0`. The body parser has been removed from the middleware, you need to register one beforehand. Take a look at the [examples](https://github.com/RisingStack/graffiti#usage).

**Comment by zopf** [comment]
Sorry for the delay!  Was traveling.

Same issue with 3.0.1 and .2.  The body parsing works properly, but we're still getting a this.request.body.variables which is a *string*.  That's the proper format for GraphiQL, but it's the wrong format for GraphQL.

GraphiQL requires `variables` to be a string.
GraphQL requires `variables` to be an object.
So, just need to parse variables string to object before it hits GraphQL.

Example after-body-parsing input:
```
{ query: 'mutation addPhotoRecord($input: addPhotoRecordInput!) {\n  addPhotoRecord(input: $input) {\n    changedPhotoRecordEdge {\n      node {\n        id,\n        photo {\n          photoURL\n        }\n      }\n    }\n    clientMutationId\n  }\n}\n }\n',
  variables: '{ \n  "input": {\n    "kind": "PhotoRecord",\n    "photo": "56aa944aeca0f60651df0ba8",\n    "clientMutationId": "123123123"\n  }\n}' }
```

Example updated handler:
```
const parsedVariables = (typeof variables === 'string' && variables.length > 0) ?
    JSON.parse(variables) : variables;
this.body = yield graphql(schema, query, this, parsedVariables);
```

**Comment by zopf** [comment]
Here's a test:

GraphQL input:
```
mutation m($input: addPetInput!) {
  addPet(input: $input) {
    changedPetEdge {
      node {
        name
        type
        age
      }
    }
  }
}
```

With variables:
```
{
  "input":{
  	"name": "Test1",
    "type": "Dog",
    "age": 5,
    "clientMutationId": "abcdef"
  }
}
```

Without the fix, I get:
```
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "Variable \"$input\" of required type \"addPetInput!\" was not provided."
}
```

With the fix, I get:
```
{
  "data": {
    "addPet": {
      "changedPetEdge": {
        "node": {
          "name": "Test1",
          "type": "Dog",
          "age": 5
        }
      }
    }
  }
}
```

PR incoming shortly...
