### ISSUE TITLE
Authorization? Security? 

### ISSUE THREAD

**Issue by Deadarius** [RisingStack/graffiti#20]
Let's say I have records that only certain users supposed to have access to, is there any current way to specify such limitations?

**Comment by tothandras** [comment]
You can implement it with resolve hooks.

**Comment by Deadarius** [comment]
Yes, but how do I get access to those hooks with graffiti? Correct me if I wrong, but I thought it generates graphql schema based on mongoose(or other) schema, therefore there is no way to customise resolve hooks?

**Comment by tothandras** [comment]
here: https://github.com/RisingStack/graffiti-mongoose/blob/master/README.md#resolve-hooks
