### ISSUE TITLE
Example with koa-router

### ISSUE THREAD

**Issue by sibeliusseraphini** [RisingStack/graffiti#22]
Is there any example of using this package with https://github.com/alexmingoia/koa-router ?

**Comment by tothandras** [comment]
@sibeliusseraphini It's just another middleware, just like `graffiti`. I think there won't be any problem using the two together.

**Comment by sibeliusseraphini** [comment]
I think my problem is that the koa of graffiti is not the Koa@2 (using async await)

I will try to figure it out how to do it for koa@2 and I will try to send a PR for this

**Comment by tothandras** [comment]
https://github.com/RisingStack/graffiti/blob/master/package.json#L51

**Comment by sibeliusseraphini** [comment]
so, why are you using a generator instead of an async function on the koa graffiti middleware?

**Comment by tothandras** [comment]
it shouldn't matter

**Comment by sibeliusseraphini** [comment]
the problem is that /graphql endpoint is hardcoded (mine is /api/graphql)

I've solved using directly with koa-router:


```js
import { graphql } from 'graphql';
import { renderGraphiQL } from '../../graphql/util';
import { schema, graphiql } from '../../graphql';

function accepts(ctx, type) {
  return ctx.headers && ctx.headers.accept && ctx.headers.accept.includes(type);
}

export default (router) => {
  router
    .get('/graphql',
      async ctx => {
        const body = ctx.request.body;
        const { query, variables } = Object.assign({}, body, ctx.query);

        if (accepts(ctx, 'html') && graphiql) {
          ctx.body = renderGraphiQL({ query, variables });
        } else if (query && query.includes('mutation')) {
          ctx.status = 406;
          ctx.body = 'GraphQL mutation only allowed in POST request.';
        }
      }
    )
    .post('/graphql',
      async ctx => {
        const body = ctx.request.body;
        const { query, variables } = Object.assign({}, body, ctx.query);

        ctx.body = await graphql(schema, query, ctx, variables);
      }
    );
};
```

thanks for your help

**Comment by Yangzhilang** [comment]
thanks a lot, it help me.
