### ISSUE TITLE
Koa tests don't actually test

### ISSUE THREAD

**Issue by zopf** [RisingStack/graffiti#24]
The koa tests in `src/koa/koa.spec.js` use generator functions.  The standard mocha installation does not support generators... because of that, the tests *always* pass, since the generators successfully return an iterator (whose `next()` function is never called), even if an `expect` condition should fail (since it is actually never run).

My suggestion is to use https://github.com/blakeembrey/co-mocha
You can simply `npm install --save-dev co-mocha`, then just add `--require co-mocha` to the "test" command in package.json.

`co-mocha` monkey-patches mocha to properly handle generators.

**Comment by tothandras** [comment]
@zopf Thanks for the report! Sorry that I haven't responded yet, see #26.

**Comment by zopf** [comment]
:) glad to help.  lgtm
