### ISSUE TITLE
How do you mutate nested object using graphql?

### ISSUE THREAD

**Issue by keonkim** [RisingStack/graffiti#29]
I have a mongoose schema like the one below:
```
import mongoose from 'mongoose'

const ProjectSchema = new mongoose.Schema({
  name: {
    type: String
  },
  owner: {
    type: String
  },
  member: {
    type: String
  },
  updatedDate: {
    type: Date
  },
  description: {
    type: String
  },
  folder: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Folder'
  },
  dataSources: [{
    name: {
      type: String
    },
    updatedDate: {
      type: Date
    },
  }],
  propjectHistory: [{
    no: {
      type: Number
    },
    member: {  // is this reference or just a string?
      type: String
    },
    action: {
      type: String
    },
    updatedDate: {
      type: Date
    },
  }]
})

const Project = mongoose.model('Project', ProjectSchema)
```
And I integrated with graphql using graffiti and graffiti-mongoose. However, the Graphiql documentation shows that I only have the ones below:

```
addProject(input: addProjectInput!):

name: String
owner: String
member: String
updatedDate: Date
description: String
folder: ID
clientMutationId: String!
```

I could successfully add project with a mutation query only using those parameters, but it seems that I cannot even send mutation query with projectHistory and dataSource, which are embedded inside project schema.

However, I can access projectHistory and dataSource when I send find queries.

I can't find any documentation about the problem.

**Comment by chrisabrams** [comment]
I'd like to second this question. I can't seem to find any examples about how to do this.

It would be great to see an example of a schema that can mutate a nested field.

I've got a very similar question over at the [graph-js](https://github.com/graphql/graphql-js/issues/357) repo.

**Comment by tothandras** [comment]
I think you can solve it with multiple mutations using the ID in the response of the first one.

**Comment by keonkim** [comment]
Thanks, I believe the latest update for the mongoose-graffiti solved  the problem
