### ISSUE TITLE
graphql 0.5.0 compatibility ?

### ISSUE THREAD

**Issue by dmolinarius** [RisingStack/graffiti#30]
Currently available graphql version is 0.5.0, but graffiti is peerDependent on graphql@^0.4.17 
Is compatibility possible or planned or should we stick to graphql 0.4.17 ?

**Comment by tothandras** [comment]
Some of the arguments changed in the resolve function. Will support it soon.

**Comment by tothandras** [comment]
@dmolinarius It should be working with version `3.0.4`. Please test it! Thank you!

**Comment by dmolinarius** [comment]
@tothandras Thanks a lot but I finally came to the conclusion that Relay was overkill for the application I develop. Using Redux lets me use a much simpler graphQL schema than needed by Relay and provided by graffiti. But definitely will keep an eye on it.
