### ISSUE TITLE
Custom rootValue and context parameters for graphql

### ISSUE THREAD

**Issue by shenyzore** [RisingStack/graffiti#31]
HI, i saw this lib pass the same `reques`t object in `graphql` function at the 3rd and 4th parameters which are `rootValue` and `context`.
Why not make it customizable so we can pass the `rootValue` and `context` parameters for `graphql`.

**Comment by tothandras** [comment]
Hi @shenyzore,
sorry for the delay, I am really short on time recently. I've added the possibility to pass in a custom context object (see readme). Would you like me to add support for function too? What parameters should it get (eg. request)?

**Comment by tothandras** [comment]
I've done it poorly.. Working on it now. :)

**Comment by tothandras** [comment]
Take a look at version `3.1.1`.

**Comment by shenyzore** [comment]
Thanks for your reply, i think it works for me.
