### ISSUE TITLE
SQL / Bookshelf.js progress

### ISSUE THREAD

**Issue by burkhardr** [RisingStack/graffiti#5]
Hi,

First, let me say that I love what you've done with the mongoose adapter.

I'm currently converting a project to graphQL that already uses bookshelf.js and stumbled upon graffiti, so I was curious as to what the current progress / ETA is and whether you could do with a hand finishing it.

**Comment by brysgo** [comment]
https://github.com/brysgo/graphql-bookshelf

**Comment by hekike** [comment]
hi @burkhardr, we didn't do real progress with Bookshelf support yet, I recommend currently to go with @brysgo's lib.

**Comment by hekike** [comment]
@burkhardr we are concentrating for the `mongoose` ORM currently. After that we start to extend it for different databases.

**Comment by hardchor** [comment]
@hekike Yes, I know (I'm trying to contribute as and when time allows). Just wanted to help cleaning up a bit to avoid the broken window problem (http://blog.codinghorror.com/the-broken-window-theory/)
