### ISSUE TITLE
What do the models look like?

### ISSUE THREAD

**Issue by mnpenner** [RisingStack/graffiti#6]
Your example is incomplete. You have

```js
app.use(graffiti.express({
  prefix: '/graphql',
  adapter: graffitiMongoose,
  models: [User, Cat]
}));
```

But don't tell us what `User` and `Cat` look like. That's kind of important, isn't it?

Is there a mapping between the models and the database? Or does `graffiti` expose all DB fields? Is that not a security risk? 

How does it handle relationships? Or it doesn't, because it only supports Mongo documents which already hold the relationships?

**Comment by jeremy-hunter** [comment]
The models are available in the example app: https://github.com/RisingStack/graffiti-example

**Comment by hekike** [comment]
@mnpenner @jeremy-hunter thanks for the help! Yes these the adapter related models, in this case `mongoose` models while you are using `graffiti` with the `graffiti-mongoose` adapter.
