### ISSUE TITLE
npm install @risingstack/graffiti error

### ISSUE THREAD

**Issue by thucnc** [RisingStack/graffiti#9]
I got below error when trying to install graffiti:
404 https://registry.npmjs.org/risingstack/graffiti
npm ERR! TypeError: Cannot read property 'latest' of undefined

please help.

P.S: I think the package is missing some meta-data, such as the latest attribute (reference: https://registry.npmjs.org/koa)

**Comment by gergelyke** [comment]
which npm version are you using?

**Comment by thucnc** [comment]
Yeah, I did upgrade my node and npm then the lib works nicely.
Thanks

**Comment by gergelyke** [comment]
great!
